### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by oskarwrobel** [oskarwrobel/2020-live-illustration#1]
### Must have
- [x] Favicon
- [x] og metadata
- [x] Remove noindex, nofollow
- [x] Analytics (events)
- [x] TV News animation
- [x] Fix oscar ClipMask
- [x] Made browser "back button" and Esc press to work with animation
- [x] Netflix channel animation
- [x] Recalculate plane banner width after the font is fully loaded
- [ ] Recalculate animations when going back from a sub-page - https://github.com/oskarwrobel/2020-live-illustration/issues/6

### Nice to have
- [ ] More animations to Oscar and Drawer pages
- [ ] Add animation to light toggler - https://github.com/oskarwrobel/2020-live-illustration/issues/5
- [ ] Add animation to postcard - https://github.com/oskarwrobel/2020-live-illustration/issues/4
- [ ] Add support for gyroscope - https://github.com/oskarwrobel/2020-live-illustration/issues/3
